---
core:
    num_workers: 100

inventory:
    plugin: nornir.plugins.inventory.simple.SimpleInventory
    options:
        host_file: "hostschange.yaml"
        group_file: "groups.yaml"
        defaults_file: "defaults.yaml"
